import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import client from "../apollo_client";
import { gql } from "@apollo/client";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>hello</h1>
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const {data,loading} = await client.query({
    query: gql`
      query Query {
        getUsers {
          name
          email
        }
      }
    `,
  });
  console.log(data);

  return {
    props:{
      data
    }
  }
};
